### PR TITLE
Bumped ffmpeg version from 3 to 4

### PR DESCRIPTION
**Pull request by jkubo**

### CODE REVIEW

**Comment by jkubo** [comment]
@googlebot recheck please!

**Comment by jkubo** [comment]
@googlebot I signed it!

**Comment by APratham** [comment]
Hi @jkubo, have you used the Video Intelligence API to build a streaming solution on Google Cloud? I wanted to know if there are any tutorials on this apart from the official documentation. Also it would be great if you can also send me a link to your solution built on Google Cloud Platform

**Comment by APratham** [comment]
@cdibona @dberlin Can you please consider this PR? It will be great because without it the Dockerfile won't build

**Pull request merged**
